Correccion de archivos
Mauricio-Rubio/Test pull request #2
Opened 2022-01-04 23:54 UTC by Mauricio-Rubio

Esos archivos de debían estar en Master

2022-01-04 23:56 UTC, TheMotherFucker29 approved these changes

2022-01-04 23:59 UTC, TheMotherFucker29 requested changes
Esos archivos debian estar integrados en un solo txt

2022-01-05 00:04 UTC, Mauricio-Rubio commented
Haz tu el merge

2022-01-05 00:06 UTC, TheMotherFucker29 approved these changes
Perfecto

2022-01-05 00:07 UTC, merged